import { Product, Want, ForumPost, ChatRoom } from "./types";

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: "prod_mine_1",
    name: "Sách Kinh Tế Học Vi Mô HOU (Giáo trình Bạn)",
    category: "Sách & Giáo trình",
    price: 35000,
    originalPrice: 110000,
    condition: "Còn mới 95%",
    description: "Sách học của tôi kì trước, bìa kính sạch đẹp không tì vết, có đầy đủ đề thi khảo sát của trường HOU lấy hên thi đạt điểm A.",
    images: ["https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80"],
    school: "Đại học Mở Hà Nội",
    author: "Nguyễn Thu Hạ (Bạn)",
    authorId: "user_client_default",
    isStudentVerified: true,
    views: 18,
    likes: 3,
    status: "Đang bán",
    suitabilityScore: 99,
    tags: ["Giáo trình chính", "Điểm cao", "Mới tinh"],
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod_mine_2",
    name: "Quạt Hộp Để Bàn Học KTX Senko",
    category: "Đồ dùng phòng trọ",
    price: 120000,
    originalPrice: 280000,
    condition: "Cũ tốt 80-85%",
    description: "Quạt bàn Senko gọn nhẹ, làm mát đằm phòng trọ 12-15m2 cực kỳ êm dể chịu, phích cắm 2 chân tiện lợi, nhượng lại để chuyển sang KTX ở.",
    images: ["https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&auto=format&fit=crop&q=80"],
    school: "Đại học Mở Hà Nội",
    author: "Nguyễn Thu Hạ (Bạn)",
    authorId: "user_client_default",
    isStudentVerified: true,
    views: 29,
    likes: 6,
    status: "Đang bán",
    suitabilityScore: 96,
    tags: ["Hoạt động tốt", "Gọn nhẹ", "Mùa nóng"],
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod_1",
    name: "Sách Giáo Trình Kinh Tế Vĩ Mô - FTU",
    category: "Sách & Giáo trình",
    price: 45000,
    originalPrice: 120000,
    condition: "Còn mới 90%",
    description: "Sách giáo trình mới học kỳ trước, không bị nháp bẩn nhiều, chỉ highlight vài dòng chương 3. Rất thích hợp cho các bạn K62 FTU chuẩn bị học môn này.",
    images: ["https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80"],
    school: "Đại học Ngoại Thương",
    author: "Nguyễn Văn Hùng",
    authorId: "user_student_hung",
    isStudentVerified: true,
    views: 42,
    likes: 8,
    status: "Đang bán",
    suitabilityScore: 95,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "prod_2",
    name: "Tai Nghe Chống Ồn Sony WH-1000XM4",
    category: "Thiết bị công nghệ",
    price: 3200000,
    originalPrice: 6500000,
    condition: "Cũ tốt 80-85%",
    description: "Tai nghe chống ồn siêu tốt, đệm tai hơi sờn nhẹ nhưng âm thanh và pin nguyên bản vẫn nghe được hơn 20 tiếng. Nhượng lại cho bạn nào ôn thi thư viện chống ồn tốt.",
    images: ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop&q=80"],
    school: "Đại học Bách Khoa Hà Nội",
    author: "Lê Minh Tuấn",
    authorId: "user_student_tuan",
    isStudentVerified: true,
    views: 128,
    likes: 24,
    status: "Đang bán",
    suitabilityScore: 88,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "prod_3",
    name: "Ấm Siêu Tốc Điện Sunhouse 1.8L",
    category: "Đồ dùng phòng trọ",
    price: 90000,
    originalPrice: 220000,
    condition: "Cũ tốt 80-85%",
    description: "Ấm đun nước siêu nhanh 1.8L, vỏ inox bền, đun nước pha mì tôm hay pha trà đều ok, phòng trọ đổi ấm ga nên thanh lý bớt cho gọn tủ.",
    images: ["https://images.unsplash.com/photo-1594212699903-ec8a3cee50f6?w=600&auto=format&fit=crop&q=80"],
    school: "Đại học Quốc Gia Hà Nội",
    author: "Trần Thị Lan",
    authorId: "user_student_lan",
    isStudentVerified: true,
    views: 64,
    likes: 5,
    status: "Đang bán",
    suitabilityScore: 92,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "prod_4",
    name: "Bàn Học Gấp Gọn Đa Năng Cho Giường KTX",
    category: "Đồ dùng phòng trọ",
    price: 35000,
    originalPrice: 85000,
    condition: "Còn mới 95%",
    description: "Bàn gấp gọn chân sắt cứng cáp, có khe cắm iPad và chỗ để cốc nước, mặt bàn giả vân gỗ sáng đẹp sạch sẽ, tiện sử dụng ngay trên giường ktx.",
    images: ["https://images.unsplash.com/photo-1519125323398-675f0ddb6308?w=600&auto=format&fit=crop&q=80"],
    school: "Đại học Kinh tế Quốc dân",
    author: "Phạm Minh Đức",
    authorId: "user_student_duc",
    isStudentVerified: true,
    views: 93,
    likes: 12,
    status: "Đang bán",
    suitabilityScore: 97,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod_5",
    name: "Chuột Không Dây Logitech Pebble M350",
    category: "Thiết bị công nghệ",
    price: 180000,
    originalPrice: 400000,
    condition: "Còn mới 90%",
    description: "Chuột kết nối bluetooth và tăm nhận USB đều được, bấm cực kỳ êm không tiếng động (silent click), màu cát hồng nhạt siêu đẹp, ít hao pin.",
    images: ["https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=600&auto=format&fit=crop&q=80"],
    school: "Đại học Ngoại Thương",
    author: "Đỗ Thùy Linh",
    authorId: "user_student_linh",
    isStudentVerified: true,
    views: 31,
    likes: 4,
    status: "Đang chờ",
    suitabilityScore: 90,
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "prod_6",
    name: "Sách Giáo Trình Kinh Tế Lượng - NEU",
    category: "Sách & Giáo trình",
    price: 55000,
    originalPrice: 110000,
    condition: "Còn mới 95%",
    description: "Sách Kinh tế lượng trường NEU học kì mới, sách bao kiếng bọc góc cẩn thận, không viết bút mực mực đỏ gì cả, tặng kèm tập đề thi thử kỳ trước.",
    images: ["https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=600&auto=format&fit=crop&q=80"],
    school: "Đại học Kinh tế Quốc dân",
    author: "Nguyễn Anh Minh",
    authorId: "user_student_minh",
    isStudentVerified: true,
    views: 55,
    likes: 14,
    status: "Đang bán",
    suitabilityScore: 93,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "prod_7",
    name: "Máy Tính Bỏ Túi Casio FX-580VN X",
    category: "Thiết bị công nghệ",
    price: 380500,
    originalPrice: 750000,
    condition: "Còn mới 90%",
    description: "Máy tính cầm tay Casio đầy đủ nắp đậy, chữ số phím bấm rõ ràng sắc nét, phục vụ tốt các kỳ thi THPT hay các môn Toán Cao Cấp và Kinh tế lượng đại học.",
    images: ["https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=600&auto=format&fit=crop&q=80"],
    school: "Đại học Bách Khoa Hà Nội",
    author: "Trần Thế Phong",
    authorId: "user_student_phong",
    isStudentVerified: true,
    views: 185,
    likes: 31,
    status: "Đang bán",
    suitabilityScore: 91,
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "prod_8",
    name: "Đèn Học Để Bàn Chống Cận Xiaomi LED",
    category: "Thiết bị công nghệ",
    price: 190000,
    originalPrice: 380000,
    condition: "Còn mới 95%",
    description: "Đèn bàn thông minh Xiaomi kết nối được wifi điều chỉnh độ sáng qua app Mihome cực êm dịu, không nhấp nháy, giúp bảo vệ mắt tốt khi thức khuya ôn thi.",
    images: ["https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&auto=format&fit=crop&q=80"],
    school: "Đại học Quốc gia TP.HCM",
    author: "Vũ Bảo Ngọc",
    authorId: "user_student_ngoc",
    isStudentVerified: true,
    views: 79,
    likes: 18,
    status: "Đang bán",
    suitabilityScore: 94,
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "prod_9",
    name: "iPad Air 4 64GB kèm Bút Cảm Ứng Wifi",
    category: "Thiết bị công nghệ",
    price: 7400000,
    originalPrice: 13500000,
    condition: "Còn mới 90%",
    description: "iPad dùng mượt mà, bao gồm sạc cáp zin và bút stylus ghi chú bài giảng siêu nhạy. Đã dán cường lực nhám chống vân tay thuận tiện cho vẽ/viết.",
    images: ["https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=600&auto=format&fit=crop&q=80"],
    school: "Đại học Ngoại Thương",
    author: "Phan Khánh Vy",
    authorId: "user_student_vy",
    isStudentVerified: true,
    views: 312,
    likes: 67,
    status: "Đang bán",
    suitabilityScore: 89,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "prod_10",
    name: "Bàn Là Hơi Nước Cầm Tay Philips 1000W",
    category: "Đồ dùng phòng trọ",
    price: 240000,
    originalPrice: 620000,
    condition: "Còn mới 95%",
    description: "Bàn ủi hơi nước cầm tay nhỏ gọn, là phẳng quần áo sơ mi đi học chỉ trong 1 phút, hơi nước phun mạnh kháng khuẩn, an toàn tất cả chất vải.",
    images: ["https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=600&auto=format&fit=crop&q=80"],
    school: "Học viện Ngoại giao",
    author: "Ngô Hoàng Nam",
    authorId: "user_student_nam",
    isStudentVerified: true,
    views: 62,
    likes: 9,
    status: "Đang bán",
    suitabilityScore: 96,
    createdAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  },
  {
    id: "prod_11",
    name: "Kệ Giày Gỗ Thông 5 Tầng Hàn Quốc",
    category: "Đồ dùng phòng trọ",
    price: 130000,
    originalPrice: 290000,
    condition: "Còn mới 90%",
    description: "Kệ giày gỗ thông tự nhiên cứng cáp, chịu lực tốt, sức chứa lên tới 15 - 18 đôi giày dép. Đặt ở góc phòng trọ vô cùng gọn gàng và thẩm mỹ.",
    images: ["https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=600&auto=format&fit=crop&q=80"],
    school: "Đại học Kinh tế TP.HCM",
    author: "Lê Nhật Huy",
    authorId: "user_student_huy",
    isStudentVerified: true,
    views: 110,
    likes: 22,
    status: "Đang bán",
    suitabilityScore: 92,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "prod_12",
    name: "Bình Giữ Nhiệt Lock&Lock 500ml Inox",
    category: "Đồ dùng cá nhân khác",
    price: 95000,
    originalPrice: 250000,
    condition: "Mới tinh 100% (Seal/Hộp)",
    description: "Bình giữ nhiệt thương hiệu Lock&Lock inox 316 cao cấp, giữ ấm tối đa 12 tiếng, giữ lạnh 24 tiếng. Hàng quà tặng hội thảo chưa qua sử dụng nguyên hộp.",
    images: ["https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&auto=format&fit=crop&q=80"],
    school: "Đại học Sư phạm Hà Nội",
    author: "Nguyễn Mai Phương",
    authorId: "user_student_phuong",
    isStudentVerified: true,
    views: 84,
    likes: 19,
    status: "Đang bán",
    suitabilityScore: 95,
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "prod_13",
    name: "Bàn Phím Cơ RK61 Blue Switch Bluetooth",
    category: "Thiết bị công nghệ",
    price: 450000,
    originalPrice: 900000,
    condition: "Còn mới 90%",
    description: "Bàn phím cơ layout 61 phím siêu nhỏ gọn xếp vào balo mang đi cafe hay thư viện trường tiện lợi. Led vàng đơn sắc cực chất, pin sạc bền bỉ.",
    images: ["https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&auto=format&fit=crop&q=80"],
    school: "Học viện Công nghệ Bưu chính Viễn thông",
    author: "Cao Đình Hùng",
    authorId: "user_student_chinh",
    isStudentVerified: true,
    views: 145,
    likes: 38,
    status: "Đang bán",
    suitabilityScore: 90,
    createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "prod_14",
    name: "Gương Đèn Led Tròn Trang Điểm Cảm Ứng",
    category: "Đồ dùng cá nhân khác",
    price: 75000,
    originalPrice: 180000,
    condition: "Còn mới 95%",
    description: "Gương trang điểm tròn để bàn, có tích hợp viền đèn LED màu sáng trắng tự nhiên điều chỉnh 3 mức cảm ứng xịn xò, mặt gương nét chống mốc.",
    images: ["https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&auto=format&fit=crop&q=80"],
    school: "Học viện Báo chí và Tuyên truyền",
    author: "Đặng Khánh Huyền",
    authorId: "user_student_huyen",
    isStudentVerified: true,
    views: 66,
    likes: 15,
    status: "Đang bán",
    suitabilityScore: 93,
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "prod_15",
    name: "Sổ Tay Từ Vựng Tiếng Anh Giao Tiếp IELTS",
    category: "Sách & Giáo trình",
    price: 25000,
    originalPrice: 70000,
    condition: "Cũ tốt 80-85%",
    description: "Tổng hợp từ vựng Collocation, Idioms thông dụng của ban học viên 7.5 IELTS đóng quyển sành điệu, in ấn sắc nét dễ theo dõi nhanh qua kẹp thẻ.",
    images: ["https://images.unsplash.com/photo-1517842645767-c639042777db?w=600&auto=format&fit=crop&q=80"],
    school: "Đại học Mỹ thuật Công nghiệp",
    author: "Hoàng Ngân Hà",
    authorId: "user_student_ha",
    isStudentVerified: false,
    views: 48,
    likes: 7,
    status: "Đang bán",
    suitabilityScore: 85,
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
  }
];

export const INITIAL_WANTS: Want[] = [
  {
    id: "want_1",
    title: "Tìm mua Giáo trình Kinh tế lượng",
    category: "Sách & Giáo trình",
    budget: "50,050đ - 80,000đ",
    schoolFilter: "Đại học Ngoại Thương",
    description: "Cần tìm giáo trình Kinh tế lượng FTU xuất bản năm 2022 trở lại đây, có viết nháp cũng được miễn là không rách trang.",
    buyer: "Trần Anh Quân",
    buyerSchool: "Đại học Ngoại Thương",
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "want_2",
    title: "Tìm loa Bluetooth Bass mạnh phòng trọ",
    category: "Thiết bị công nghệ",
    budget: "200,000đ - 400,000đ",
    schoolFilter: "Bách Khoa / Xây Dựng",
    description: "Phòng trọ 15m2 muốn mua một chiếc loa nghe nhạc cũ loại JBL Go, Sony Extra Bass cũ hoặc hàng Hoco, âm thanh không rè, pin cầm lâu chút.",
    buyer: "Vũ Hoàng Lâm",
    buyerSchool: "Đại học Bách Khoa Hà Nội",
    createdAt: new Date().toISOString(),
  },
  {
    id: "want_3",
    title: "Mua Quạt tích điện gấp gọn cũ",
    category: "Đồ dùng phòng trọ",
    budget: "100,000đ - 150,000đ",
    schoolFilter: "Mọi trường",
    description: "Phòng hay bị mất điện đột ngột mùa hè, cần mua quạt tích điện cũ xài chống cháy qua đêm.",
    buyer: "Nguyễn Thu Hà",
    buyerSchool: "Đại học Sư phạm Hà Nội",
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  }
];

export const INITIAL_FORUM_POSTS: ForumPost[] = [
  {
    id: "forum_1",
    title: "Gom mua chung túi nước giặt Omo 3.6kg Coopmart giảm 40%",
    tag: "Gom mua chung",
    author: "Nguyễn Thùy Dung",
    school: "Đại học Ngoại Thương",
    content: "Chào mọi người, Coopmart gần trường đang có deal mua 2 túi nước giặt OMO Matic giảm sâu, tính ra chỉ 110k/túi 3.6kg (giá gốc 170k). Mình chỉ xài một túi nên muốn gom chung với 1 bạn khác lấy chung cho rẻ. Nhận hàng tại cổng trường FTU chiều mai nhé!",
    upvotes: 24,
    commentsCount: 2,
    comments: [
      { id: "comment_1", author: "Lê Minh Tuấn", school: "Đại học Bách Khoa Hà Nội", content: "Kèo thơm quá bạn ơi! Mình đăng ký chung 1 túi với nhé.", createdAt: new Date(Date.now() - 4 * 60 * 1000).toISOString() },
      { id: "comment_2", author: "Đỗ Thùy Linh", school: "Đại học Ngoại Thương", content: "Nếu còn suất thì mình cũng muốn mua chung nha, nước giặt Omo xài rất thơm.", createdAt: new Date(Date.now() - 2 * 60 * 1000).toISOString() }
    ],
    joinedUsers: ["user_student_linh"],
    targetMembers: 5,
    currentPrice: 110000,
    originalPrice: 170000,
    productImage: "https://images.unsplash.com/photo-1584346133934-a3afd2a33c4c?w=600&auto=format&fit=crop&q=80",
    isGroupBuyCompleted: false,
    createdAt: new Date(Date.now() - 5 * 1000 * 60).toISOString(),
  },
  {
    id: "forum_2",
    title: "Tìm bạn nam ở ghép KTX Mỹ Đình - phòng sạch sẽ văn minh",
    tag: "Phòng trọ & Ở ghép",
    author: "Lý Quốc Khánh",
    school: "Đại học Quốc Gia Hà Nội",
    content: "Mình cần tìm 1 bạn nam ở ghép phòng KTX Mỹ Đình, phòng hiện tại có 2 người, rộng rãi, đầy đủ điều hòa tủ lạnh nước nóng. Chi phí chia đôi tầm 400k/tháng cả điện nước. Ưu tiên các bạn không hút thuốc, giữ gìn vệ sinh và tôn trọng giờ giấc sinh hoạt chung.",
    upvotes: 18,
    commentsCount: 1,
    comments: [
      { id: "comment_3", author: "Nguyễn Anh Minh", school: "Đại học Kinh tế Quốc dân", content: "Phòng còn trống không bạn? Mình khóa K62 vừa lên Hà Nội học muốn qua xem phòng.", createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString() }
    ],
    joinedUsers: [],
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "forum_3",
    title: "Tìm nhóm đăng ký giải chạy Uni-Run 2024 nhận Discount 20%",
    tag: "Hoạt động & Sự kiện",
    author: "Đoàn Văn Nam",
    school: "Đại học Bách Khoa Hà Nội",
    content: "Giải chạy sinh viên Uni-Run sắp tới có chính sách đăng ký nhóm từ 10 người trở lên giảm 20% giá vé BIB. Hiện tại nhóm mình có 6 bạn rồi, cần thêm 4 bạn nữa đóng tiền mua chung cho rẻ. Cự ly chạy 5km và 10km quanh Hồ Tây nha mọi người ơi!",
    upvotes: 35,
    commentsCount: 0,
    comments: [],
    joinedUsers: ["user_client_default"],
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "forum_4",
    title: "Pass lại tài khoản ôn thi IELTS xịn sò - còn lẻ 3 tháng",
    tag: "Học tập & Tài liệu",
    author: "Hồ Anh Thư",
    school: "Đại học Ngoại Thương",
    content: "Pass lại tài khoản học từ vựng và luyện đề Prep.vn còn hạn sử dụng 3 tháng rưỡi. Có cam kết chấm chữa bài IELTS Writing & Speaking bằng AI. Thích hợp cho bạn nào đang ôn thi gấp đợt tháng 8 này.",
    upvotes: 12,
    commentsCount: 1,
    comments: [
      { id: "comment_4", author: "Cao Đình Hùng", school: "Học viện Bưu chính Viễn thông", content: "Tài khoản có được đổi mật khẩu không bạn? Giá pass lại nhiêu á?", createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString() }
    ],
    joinedUsers: [],
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
  }
];

export const INITIAL_CHAT_ROOMS: ChatRoom[] = [
  {
    roomId: "room_1",
    product: {
      id: "prod_1",
      name: "Sách Giáo Trình Kinh Tế Vĩ Mô - FTU",
      price: 45000,
      image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80",
      school: "Đại học Ngoại Thương"
    },
    buyer: {
      id: "user_client_default",
      name: "Sinh viên Nguyễn Thu Hạ (Bạn)",
      school: "Đại học Mở Hà Nội",
    },
    seller: {
      id: "user_student_hung",
      name: "Nguyễn Văn Hùng",
      school: "Đại học Ngoại Thương",
      isStudentVerified: true
    },
    messages: [
      {
        id: "msg_1",
        senderId: "user_student_hung",
        text: "Chào bạn, mình thấy bạn quan tâm đến sách Giáo trình Kinh tế vĩ mô của mình.",
        timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
      },
      {
        id: "msg_2",
        senderId: "user_client_default",
        text: "Dạ vâng ạ, sách còn mới không bạn ơi? Có nhiều nét gạch vẽ bút mực trong đó không ạ?",
        timestamp: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
      },
      {
        id: "msg_3",
        senderId: "user_student_hung",
        text: "Yên tâm nha, chỉ có highlight vài trang đầu bằng bút dạ thôi, không bị vẽ bậy đâu. Sách này mình giữ kỹ lắm.",
        timestamp: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
      }
    ]
  },
  {
    roomId: "room_2",
    product: {
      id: "prod_3",
      name: "Ấm Siêu Tốc Điện Sunhouse 1.8L",
      price: 90000,
      image: "https://images.unsplash.com/photo-1594212699903-ec8a3cee50f6?w=600&auto=format&fit=crop&q=80",
      school: "Đại học Quốc Gia Hà Nội"
    },
    buyer: {
      id: "user_client_default",
      name: "Sinh viên Nguyễn Thu Hạ (Bạn)",
      school: "Đại học Mở Hà Nội",
    },
    seller: {
      id: "user_student_lan",
      name: "Trần Thị Lan",
      school: "Đại học Quốc Gia Hà Nội",
      isStudentVerified: true
    },
    messages: [
      {
        id: "msg_1_2",
        senderId: "user_client_default",
        text: "Chào bạn Lan, ấm siêu tốc còn đun nước bình thường không ạ? Cho mình bớt xăng xe chút đỉnh nha.",
        timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "msg_2_2",
        senderId: "user_student_lan",
        text: "Đun tốt lắm bạn, sôi rất nhanh. Giá 90k là rẻ lắm rồi ấy, nhưng nếu bạn qua tận nơi ở Ký túc xá Ngoại ngữ lấy mình bớt 10k còn 80k nha.",
        timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 10 * 60 * 1000).toISOString(),
      }
    ]
  }
];
